---
title: "WebAPI01_google_map"
author: "Jilung Hsieh"
date: "2018/7/16"
output: 
  html_document: 
    number_sections: true
    highlight: textmate
    theme: spacelab
    toc: yes
editor_options: 
  chunk_output_type: inline
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# googple place api

* https://developers.google.com/places/?hl=zh-tw
* What topics can you propose?


```{r}
library(httr)
library(jsonlite)
library(dplyr)
options(stringsAsFactors = FALSE)

```



```{r}
latlng <- "25.0157838,121.5363939"
radius <- 3000
place_name <- "&name=%s"
key <- "AIzaSyCG4lihmJgwOZ41KlDjfhz3ntiswLskyYE"
url <- sprintf("https://maps.googleapis.com/maps/api/place/nearbysearch/json?location=%s&radius=%s&types=food&key=%s", latlng, radius, key)


res <- fromJSON(content(GET(url), "text", encoding = "utf-8"))

# res$results$geometry$viewport
all.df <- data.frame(name = res$results$name,
           place_id = res$results$place_id,
           lat = res$results$geometry$location$lat,
           lng = res$results$geometry$location$lng)
url.next <- paste0(url, "&pagetoken=", res$next_page_token)
```

```{r}
for(i in 1:3){
    res.next <- fromJSON(content(GET(url.next), "text", encoding = "utf-8"))
    temp.df <- data.frame(name = res.next$results$name,
           place_id = res.next$results$place_id,
           lat = res.next$results$geometry$location$lat,
           lng = res.next$results$geometry$location$lng)
    all.df <- bind_rows(all.df, temp.df)
    url.next <- paste0(url, "&pagetoken=", res.next$next_page_token)
    print(nrow(all.df))
}
length(unique(all.df$name))

browseURL(url.next)

all.df$place_id[1]
```



# get place comments
```{r}
pid <- all.df$place_id[16]
all.df$name[16]
url <- sprintf("https://maps.googleapis.com/maps/api/place/details/json?placeid=%s&key=%s", pid, key)

res <- fromJSON(content(GET(url), "text", encoding = "utf-8")) 
res$result$url
res$result$utc_offset
res$result$vicinity
```

